on:
  pull_request:
    types: [closed]
    branches:
      - master

name: Publish

jobs:

  publish:
    name: Run cargo publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Bump cargo version
        run: |
          cargo install cargo-bump
          cd label-macros
          cargo bump minor
          cd ..
          cd label
          cargo bump minor
          version=$(grep "version.*=" label/Cargo.toml | head -n 1 | cut -d '=' -f 2) && sed -i "s/path *= *\"..\/label-macros\", *version *= *\".*\"/path=\"..\/label-macros\", version=$version/" label/Cargo.toml

      - name: Publish to crates.io
        run: |
          cargo login $CARGO_DEPLOY_TOKEN
          cd label-macros
          cargo +nightly publish
          cd ..
          cd label
          sleep 15
          cargo +nightly publish
