on:
  pull_request:
    types: [closed]
    branches:
      - master

name: Publish

jobs:

  publish:
      name: Run cargo publish
      runs-on: ubuntu-latest
      steps:
        - name: Checkout sources
          uses: actions/checkout@v2

        - name: Bump cargo version
          uses: actions-rs/cargo@v1
          run: |
            cargo install cargo-bump
            cargo bump minor

        - name: Publish to crates.io
          uses: actions-rs/cargo@v1
          run: |
            cargo login $CARGO_DEPLOY_TOKEN
            cd label-macros
            cargo +nightly publish
            cd ..
            cd label
            sleep 15
            cargo +nightly publish
