on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}

      - name: Set cargo version
        run: |
          echo $RELEASE_VERSION
          export RELEASE_VERSION=$(echo $RELEASE_VERSION | cut -b 1 --complement)
          sed -i '0,/version += +".*"/{s/version += +".*"/version = "$RELEASE_VERSION"/}' label/Cargo.toml
          sed -i '0,/version += +".*"/{s/version += +".*"/version = "$RELEASE_VERSION"/}' label-macros/Cargo.toml
          sed -i "s/path *= *\"..\/label-macros\", *version *= *\".*\"/path=\"..\/label-macros\", version=\"$RELEASE_VERSION\"/" label/Cargo.toml
          cat label/Cargo.toml

      - name: Publish to crates.io
        run: |
          cargo login $CARGO_DEPLOY_TOKEN
          cd label-macros && cargo +nightly publish
          sleep 15
          cd label && && cargo +nightly publish
